// AGP 9 compiles Kotlin itself ("built-in Kotlin"), so there is no
// org.jetbrains.kotlin.android plugin here — only the compiler plugins.
import java.net.URI
import org.yaml.snakeyaml.Yaml

// SnakeYAML on the build classpath, to read settings.yml below.
buildscript {
    repositories { mavenCentral() }
    dependencies { classpath(libs.snakeyaml) }
}

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

// Instant alerts (Firebase Cloud Messaging) are optional: the plugin is only
// applied when this install's google-services.json (gitignored) is present.
// Without it the app builds and runs normally on its hourly check alone.
// Setup: docs/push-notifications.md in the web repo.
if (file("google-services.json").exists()) {
    apply(plugin = libs.plugins.google.services.get().pluginId)
}

// Private per-install settings (gitignored). See settings.example.yml.
val appSettings: Map<*, *> = rootProject.file("settings.yml").let { f ->
    if (!f.exists()) emptyMap<Any, Any>()
    else f.reader().use { Yaml().load<Any?>(it) } as? Map<*, *> ?: emptyMap<Any, Any>()
}

/** A value from settings.yml by key path, e.g. setting("server", "url"); "" if unset. */
fun setting(vararg path: String): String {
    var node: Any? = appSettings
    for (key in path) node = (node as? Map<*, *>)?.get(key)
    return node?.toString()?.trim().orEmpty()
}

// The installed app's id (settings.yml app.id). Only the id changes: the
// source package and namespace stay com.eosoclub.ourhome, so no folders move.
// It must match the package name registered in Firebase for push to work.
val appId = setting("app", "id").ifEmpty { "com.eosoclub.ourhome" }
require(Regex("""[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+""").matches(appId)) {
    "settings.yml app.id '$appId' is not a valid Android package name (e.g. com.example.ourhome)"
}

// Plain http:// is blocked by Android unless allowed per host. Only the built-in
// server (settings.yml server.url) is allowed, and only when it is http:// —
// e.g. a home-network-only install at http://192.168.1.10:3000. Written into a
// generated res/xml/network_security_config.xml, which the manifest points at.
val httpHost = setting("server", "url").let { url ->
    if (url.startsWith("http://")) URI(url).host.orEmpty() else ""
}
val generatedRes = layout.buildDirectory.dir("generated/ourhome-res").get().asFile
generatedRes.resolve("xml").apply { mkdirs() }.resolve("network_security_config.xml").writeText(
    buildString {
        appendLine("""<?xml version="1.0" encoding="utf-8"?>""")
        appendLine("<!-- Generated by build.gradle.kts from settings.yml server.url. -->")
        appendLine("<network-security-config>")
        appendLine("""    <base-config cleartextTrafficPermitted="false">""")
        appendLine("""        <trust-anchors><certificates src="system" /></trust-anchors>""")
        appendLine("    </base-config>")
        if (httpHost.isNotEmpty()) {
            appendLine("""    <domain-config cleartextTrafficPermitted="true">""")
            appendLine("""        <domain includeSubdomains="false">$httpHost</domain>""")
            appendLine("    </domain-config>")
        }
        appendLine("</network-security-config>")
    },
)

// Release signing, for builds made by the web deploy (or CI): the keystore and
// its password come from the environment, never from files in this repo.
// Without them a release build is unsigned; debug builds work as always.
val releaseKeystore = System.getenv("OURHOME_KEYSTORE")?.let { file(it) }?.takeIf { it.exists() }

android {
    namespace = "com.eosoclub.ourhome"
    compileSdk = 37

    signingConfigs {
        if (releaseKeystore != null) {
            create("release") {
                storeFile = releaseKeystore
                storePassword = System.getenv("OURHOME_KEYSTORE_PASSWORD")
                keyAlias = System.getenv("OURHOME_KEY_ALIAS") ?: "ourhome"
                keyPassword = System.getenv("OURHOME_KEY_PASSWORD") ?: System.getenv("OURHOME_KEYSTORE_PASSWORD")
            }
        }
    }

    defaultConfig {
        applicationId = appId
        // Android 12+: notification actions can require device unlock
        // (setAuthenticationRequired), which the lock-screen rules depend on.
        minSdk = 31
        targetSdk = 37
        // Builds from the web deploy pass a rising version code, so each new
        // APK installs over the last one.
        versionCode = System.getenv("OURHOME_VERSION_CODE")?.toIntOrNull() ?: 1
        versionName = System.getenv("OURHOME_VERSION_NAME") ?: "0.1.0"

        // Default server from settings.yml (server.url); blank means the
        // sign-in screen asks for it. Always editable there.
        val baseUrl = setting("server", "url")
        buildConfigField("String", "DEFAULT_BASE_URL", "\"$baseUrl\"")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            signingConfig = signingConfigs.findByName("release")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }
}

androidComponents {
    onVariants { variant ->
        variant.sources.res?.addStaticSourceDirectory(generatedRes.path)
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons.core)
    debugImplementation(libs.compose.ui.tooling)

    implementation(libs.androidx.work.runtime.ktx)
    implementation(libs.okhttp)
    implementation(libs.kotlinx.serialization.json)

    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.messaging)

    testImplementation(libs.junit)
}
